import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Clock from 'react-live-clock';
import { useEffect, useState } from 'react'

export default function Home() {
    const [hasMounted, setHasMounted] = useState(false);

  useEffect(() => {
    setHasMounted(true);
  }, []);

  if (!hasMounted) {
    return null;
  }

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

    <main className={styles.main}>
        <Clock
          format={'hh:mm:ssa'}
          style={{fontSize: '10em'}}
          ticking={true} />
    </main>
    </div>
  )
}
